module.exports = {
    "skuNumber": "7770000",
    "checkDigit": "0067866",
    "productStatusCode": "FD",
    "productShortDesc": {
      "en": "CARRIER CELEBRATION",
      "fr": "SIEGE ENF.CELEBRATIO"
    },
    "warrantyTypeCode": "A",
    "dispositionCode": "1",
    "psSubLineCode": "",
    "partNumber": "",
    "primaryVendorPartNumber": "0768N4",
    "divisionCode": "AU",
    "divisionName": "AUTOMOTIVE",
    "lobCode": "AB",
    "lineOfBusinessName": "CAR CARE & ACCESSORIES",
    "categoryCode": "116",
    "categoryName": "AUTO COMFORT",
    "subCategoryCode": "180",
    "subCategoryName": "Automotive Mats",
    "finelineCode": "18040",
    "finelineName": "Mats, Fun & Fashion",
    "lineCode": "",
    "castCharge": 0,
    "pcode": "0031712P",
    "longdesc": {
      "en": "",
      "fr": ""
    },
    "minimumOrderQty": 1,
    "MOQUOMCode": "BOX",
    "onlineOrderOnly": false,
    "brandCode": "NATIONAL, VENDOR BRAND",
    "dwoEndDate": null,
    "goodsProductTypeCode": "STD",
    "hazMatTDGClassCode": "",
    "hazMatTypeCode": "",
    "onlineDisplayEffecitveDate": null,
    "onlineDisplayEndDate": null,
    "primeVendorLocationName": "",
    "primeVendorLocationNumber": "",
    "primeVendorOrganizationName": "",
    "specialOrder": false,
    "targetSetupDate": null,
    "expressOrder": false,
    "onlineMOQ": 1,
    "repairOrderRequired": "N",
    "suppressStoreInventory": "N",
    "skuFamilySize": 1,
    "onlineActive": false,
    "goodsProductSubtypeCode": "DC",
    "consumerPackage": {
      "height": 13,
      "length": 12,
      "width": 5,
      "weight": 2,
      "dimUOMCode": "in",
      "weightUOMCode": "lb",
      "dimUOMTypeID": 104,
      "quantity": 1,
      "weightUOMTypeID": 102,
      "typeId": 152,
      "typeCode": "BOX",
      "qtyUOMTypeID": 0,
      "qtyUOMCode": "",
      "dimUomFrench": "po",
      "weightDimUomFrench": "lb"
    },
    "productId": 239545,
    "psSkuNumber": "",
    "psProductId": 0,
    "goodsProductTypeId": 69,
    "discontinued": true,
    "priceSrcTypeId": 25,
    "priceSrcCode": "CTR",
    "exclusive": false,
    "offeredByInvolvedPartyID": 2,
    "popularityCode": "",
    "MOQUOMTypeID": 152,
    "brand": {
      "typeID": 246,
      "name": {
        "en": "NATIONAL, VENDOR BRAND",
        "fr": ""
      },
      "category": {
        "id": 698,
        "code": "National",
        "name": "National"
      }
    },
    "dispositionTypeID": 72,
    "hazMatTypeID": 0,
    "hazMatTDGClassTypeID": 0,
    "productStatusTypeID": 4,
    "mfrSuggestedRetailPrice": 0,
    "fineline2Code": "40",
    "offeredByInvolvedPartyName": "Canadian Tire Retail",
    "warrantyTypeID": 494,
    "productTypeID": 1,
    "productTypeCode": "GP",
    "primeCountryOfOrigin": {
      "id": 248,
      "code": "US",
      "name": "United States"
    },
    "modelEnglishName": "",
    "modelEnglishDescription": "",
    "colourTypeID": 0,
    "colourTypecode": "",
    "assortmentarchTypeID": 0,
    "assortmentarchTypeCode": "",
    "finishDescription": {
      "en": "",
      "fr": ""
    },
    "modelFrenchName": "",
    "modelFrenchDescription": "",
    "primeCountryFrenchName": "Etats-Unis",
    "colourTypeFrench": "",
    "sizeDescription": {
      "en": "",
      "fr": ""
    },
    "colourStyleDesc": {
      "en": "",
      "fr": ""
    },
    "AMOQTrueMOQ": 0
  };
